### PR TITLE
Upload site image script

### PR DESCRIPTION
**Pull request by frankfu03**

### CODE REVIEW

**Comment by frankfu03** [comment]
Thanks for the info. I spent some time looking into the usage of xsltproc. If we are going to use xsltproc, we need to create xslt stylesheets from 15+ geodesyml xsd files. I can go ahead with this approach as advised but it may take a bit more time to complete.

**Comment by lbodor** [comment]
I have not used xslt much myself, but I thought that a single file would be enough, a single xslt file to transform an xml file. I will also have a read about xslt and see if I can come up with an example.

**Comment by lbodor** [comment]
Did you mean that the issue is with xsltproc, rather than with xslt?

**Comment by frankfu03** [comment]
No, I mean that it will take time in creating a xslt stylesheet from the 18 xsd files in GeodesyML repo.

**Comment by frankfu03** [comment]
I haven't tested xsltproc. But I wonder how to insert a full associateddocument tag into sitelog geodesyml using xsltproc. For example, can the attribute values of `gml:id` and `codeSpace` be automatically generated in the xml tags?
```
<geo:associatedDocument>
         <geo:Document gml:id="Document.947dad5d-cfe0-481f-9ff3-43be983ed79e">
            <gml:description>Antenna North Facing</gml:description>
            <gml:name codeSpace="eGeodesy/type">ALIC_ant_000_20200818T015020.jpg</gml:name>
            <gml:boundedBy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
            <geo:type codeSpace="eGeodesy/type">image/jpeg</geo:type>
            <geo:createdDate>2020-08-18T01:50:20.000Z</geo:createdDate>
            <geo:body>
               <geo:fileReference xlink:href="https://devgeodesy-webservices.geodesy.ga.gov.au/associatedDocuments/ALIC_ant_000_20200818T015020.jpg"/>
            </geo:body>
         </geo:Document>
      </geo:associatedDocument>
```

**Comment by frankfu03** [comment]
For purpose of learning more about xslt and xsltproc, I am happy to go ahead with the approach as advised.

**Comment by lbodor** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
  <xsl:stylesheet
      xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
      xmlns:geo="urn:xml-gov-au:icsm:egeodesy:0.5"
      xmlns:gml="http://www.opengis.net/gml/3.2"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      version="1.0">
      <xsl:template match="@* | node()">
          <xsl:copy>
              <xsl:apply-templates select="@* | node()"/>
          </xsl:copy>
      </xsl:template>
      <xsl:template match="geo:MoreInformation">
          <xsl:copy-of select="."/>
          <geo:associatedDocument>
              <geo:Document gml:id="Document.54ba8245-26be-41fe-aa4c-26632d1ee3d5">
              <gml:description>Antenna North Facing</gml:description>
              <gml:name codeSpace="eGeodesy/type">ADE1_ant_000_20200818T015336.png</gml:name>
              <gml:boundedBy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
              <geo:type codeSpace="eGeodesy/type">image/png</geo:type>
              <geo:createdDate>2020-08-18T01:53:36.000Z</geo:createdDate>
              <geo:body>
                  <geo:fileReference xlink:href="https://devgeodesy-webservices.geodesy.ga.gov.au/associatedDocuments/ADE1_ant_000_20200818T015336.png"/>
              </geo:body>
              </geo:Document>
          </geo:associatedDocument>
      </xsl:template>
  </xsl:stylesheet>
```

`xsltproc add-site-image.xslt alic.xml > alic-with-site-image.xml`

**Pull request closed without merging**
