### PR TITLE
Skeleton endpoint to use Metadata Custodian

### PR DESCRIPTION
**Pull request by umeat**
Also includes change merged into master from recent prod release branch.

### CODE REVIEW

**Comment by umeat** [comment]
I agree. Does this involve much more than just setting the version in the root pom file to 0.4.0.SNAPSHOT?

Snapshot is meant to be latest unstable, right?

**Comment by lbodor** [comment]
Yes, 0.4.0-SNAPSHOT in the pom.xml is all. That would the latest unstable/snapshot version, it means going towards 0.4.0. Usually the first commit you make on master after making a release branch is to change the version of X to (X+1)-SNAPSHOT.

Often people combine setting the version in the pom and making a release with creating a tag v0.3.0.

**Comment by lbodor** [comment]
But, there will be a few pom files to change, because gws consists of a few maven submodules, maven parent, core, web, and system tests. And all the dependencies in those pom files.

**Comment by umeat** [comment]
Should this specific change be considered a bug fix for version 0.3.0? You could look at it either way, but it doesn't break any interfaces and only modifies the behavior of a yet unused API (which was introduced in this version).

**Comment by lbodor** [comment]
Bug fix, I think

**Pull request merged**
